Repository madfish-solutions/oko-wallet, pull requests merged in 2022-12, with the labels that each got.

#181 [KL-293] Fix adding existing token
  libs/ui/src/modals/screens/token/add-token/add-token.tsx
  libs/ui/src/screens/manage-tokens/manage-tokens.tsx
Labels: ready for review

#184 [KL-373, KL-153] Add default networks and tokens
  libs/ui/src/components/icon/icon-name-map.ts
  libs/ui/src/components/icon/icon-name.enum.ts
  libs/ui/src/components/icon/networks/arbitrum.svg
  libs/ui/src/components/icon/networks/avalanche.svg
  libs/ui/src/components/icon/networks/fantom.svg
  libs/ui/src/components/icon/networks/optimism.svg
  libs/ui/src/components/icon/networks/polygon.svg
  libs/ui/src/constants/chain-ids.ts
  libs/ui/src/constants/networks.ts
  libs/ui/src/constants/rpc.ts
  libs/ui/src/constants/tokens.ts
Labels: ready for review

#185 [KL-194] Add secure screen
  libs/ui/.ts-prunerc
  libs/ui/src/components/navigator/hooks/use-show-security-sceen.hook.android.ts
  libs/ui/src/components/navigator/hooks/use-show-security-sceen.hook.ios.ts
  libs/ui/src/components/navigator/hooks/use-show-security-sceen.hook.ts
  libs/ui/src/components/navigator/navigator.tsx
  libs/ui/src/screens/splash-screen/splash-screen.styles.ts
Labels: ready for review

#193 [KL-392] Add oko logo
  libs/ui/src/components/icon/assets/mad-with-love.svg
  libs/ui/src/components/icon/assets/splash-screen.svg
  libs/ui/src/components/icon/assets/wallet-logo-placeholder-square.svg
  libs/ui/src/components/icon/assets/wallet-logo-placeholder.svg
  libs/ui/src/components/icon/icon-name-map.ts
  libs/ui/src/components/icon/icon-name.enum.ts
  libs/ui/src/modals/screens/d-app-connection-confirmation/d-app-header/d-app-header.tsx
  libs/ui/src/screens/initial/initial.styles.ts
  libs/ui/src/screens/initial/initial.tsx
  libs/ui/src/screens/settings/components/mad-fish-logo/mad-fish-logo.tsx
  libs/ui/src/screens/settings/screens/about-us/about-us.tsx
  libs/ui/src/screens/splash-screen/splash-screen.tsx
  libs/ui/src/screens/unlock-app/unlock-app.tsx
  libs/ui/src/screens/unlock-app/unlock.styles.ts
  libs/ui/src/styles/colors.ts
Labels: ready for review

#191 [KL-290] Add loader for import and creating account
  libs/ui/src/components/activity-section-list/activity-section-list.styles.ts
  libs/ui/src/components/activity-section-list/activity-section-list.tsx
  libs/ui/src/components/icon/assets/loader-snake.svg
  libs/ui/src/components/icon/icon-name-map.ts
  libs/ui/src/components/icon/icon-name.enum.ts
  libs/ui/src/components/loader/components/full-screen-loader/full-screen-loader.styles.ts
  libs/ui/src/components/loader/components/full-screen-loader/full-screen-loader.tsx
  libs/ui/src/components/loader/loader.tsx
  libs/ui/src/components/navigator/navigator.tsx
  libs/ui/src/components/protect-layout/protect-layout.styles.ts
  libs/ui/src/hooks/use-activity.hook.ts
  libs/ui/src/screens/scan-qr-code/scan-qr-code.styles.ts
  libs/ui/src/shelter/utils/create-hd-account-subscription.util.ts
  libs/ui/src/shelter/utils/create-imported-account-subscription.util.ts
  libs/ui/src/shelter/utils/import-wallet-subscription.util.ts
  libs/ui/src/store/settings/settings.actions.ts
  libs/ui/src/store/settings/settings.reducers.ts
  libs/ui/src/store/settings/settings.selectors.ts
  libs/ui/src/store/settings/settings.state.ts
Labels: ready for review

#194 [KL-389] Fix android build.Add react-native-camera and remove vision-camera
  apps/mobile/android/app/build.gradle
  apps/mobile/babel.config.json
  apps/mobile/index.js
  apps/mobile/ios/Podfile
  apps/mobile/ios/Podfile.lock
  apps/mobile/package.json
  apps/mobile/yarn.lock
  libs/ui/jest.setup.js
  libs/ui/package.json
  libs/ui/src/contract-types/factories/Erc1155Abi__factory.ts
  libs/ui/src/contract-types/factories/Erc165Abi__factory.ts
  libs/ui/src/contract-types/factories/Erc20Abi__factory.ts
  libs/ui/src/contract-types/factories/Erc721Abi__factory.ts
  libs/ui/src/mocks/native-modules.mock.ts
  libs/ui/src/mocks/react-native-permissions.mock.js
  libs/ui/src/mocks/react-native-reanimated.mock.js
  libs/ui/src/screens/scan-qr-code/scan-qr-code.native.tsx
  libs/ui/yarn.lock
Labels: ready for review

#199 [KL-383] Fix crash on selecting token without price on send page
  libs/ui/src/screens/send/screens/send-token/send-token.tsx
Labels: ready for review

#200 [KL-374, KL-400] Fix usd rate and icons for optimism and arbitrium networks
  libs/ui/src/api/constants/coin-gecko-id.ts
  libs/ui/src/components/icon/networks/arbitrum.svg
  libs/ui/src/components/icon/networks/optimism.svg
Labels: ready for review

#201 [KL-251] Add social media links
  libs/ui/src/screens/settings/constants.ts
  libs/ui/src/screens/settings/settings.styles.ts
  libs/ui/src/screens/settings/settings.tsx
Labels: ready for review

#204 [KL-352] Delete links and change descriptions on the "Add new Collectible" page
  libs/ui/src/modals/screens/add-new-collectible/add-new-collectible.tsx
Labels: ready for review

#202 [KL-394] Update token info page
  libs/ui/src/components/info-item/info-item.styles.ts
  libs/ui/src/components/info-item/info-item.tsx
  libs/ui/src/screens/token/components/token-info/token-info.tsx
Labels: ready for review

#208 [KL-185] Add loader when adding collectible
  libs/ui/src/components/collectible-image/collectible-image.tsx
Labels: ready for review

#210 [KL-199] Fix overflow input on password input
  libs/ui/src/screens/almost-done/almost-done.styles.ts
  libs/ui/src/screens/almost-done/almost-done.tsx
  libs/ui/src/screens/settings/screens/change-password/change-password.styles.ts
  libs/ui/src/screens/settings/screens/change-password/change-password.tsx
Labels: ready for review

#213 [KL-227] Fix errors messages on password change page
  libs/ui/src/screens/settings/screens/change-password/change-password.tsx
Labels: ready for review

#211 [KL-212] Fix showing error on import by seed phrase page
  libs/ui/src/modals/screens/add-account/components/seed-phrase/seed-phrase.tsx
Labels: ready for review

#173 [Kl-264] Add strategy for refreshing data
  libs/ui/src/api/coin-gecko.ts
  libs/ui/src/api/debank.ts
  libs/ui/src/components/activity-section-list/activity-section-list.tsx
  libs/ui/src/components/navigator/hooks/use-active-token-list.hook.ts
  libs/ui/src/components/navigator/hooks/use-tokens-price-info.hook.ts
  libs/ui/src/components/token-amount/token-amount.styles.ts
  libs/ui/src/components/token-amount/token-amount.tsx
  libs/ui/src/components/token/account-token/account-token.tsx
  libs/ui/src/constants/update-time.ts
  libs/ui/src/hooks/use-activity.hook.ts
  libs/ui/src/hooks/use-timer-effect.hook.ts
  libs/ui/src/interfaces/activity.interface.ts
  libs/ui/src/screens/activity/components/activity-list.tsx
  libs/ui/src/screens/wallet/hooks/use-all-user-nft.hook.ts
  libs/ui/src/store/wallet/wallet.actions.ts
  libs/ui/src/store/wallet/wallet.epics.ts
  libs/ui/src/store/wallet/wallet.selectors.ts
  libs/ui/src/utils/get-item-layout-section-list.util.ts
  libs/ui/src/utils/getSlug.uitl.ts
  libs/ui/src/utils/memoize.util.ts
Labels: ready for review

#214 [KL-223] Add border-radius for welcome screen
  libs/ui/src/screens/initial/initial.styles.ts
  libs/ui/src/screens/unlock-app/unlock.styles.ts
Labels: ready for review

#217 [KL-244] On press enter unlock app on extension and mobile
  libs/ui/src/components/text-input/text-input.tsx
  libs/ui/src/hooks/use-unlock.hook.ts
  libs/ui/src/screens/unlock-app/unlock-app.tsx
Labels: ready for review

#215 [KL-237] Fix editing empty account name
  libs/ui/src/modals/hooks/use-validate-account-field.hook.ts
  libs/ui/src/modals/screens/edit-account/edit-account.tsx
Labels: ready for review

#219 [KL-341] Align eye icon in password input
  libs/ui/src/screens/settings/screens/change-password/change-password.styles.ts
Labels: ready for review

#212 [KL-162] Fix error messages when token was added
  libs/ui/src/modals/screens/token/add-token/add-token.tsx
Labels: ready for review

#218 [KL-320] Rename initial page to welcome
  apps/extension-e2e/src/page-objects/welcome.page.ts
  libs/ui/src/components/navigator/navigator.tsx
  libs/ui/src/components/wallet-creation-container/wallet-creation-container.tsx
  libs/ui/src/enums/sreens.enum.ts
  libs/ui/src/screens/welcome/welcome.styles.ts
  libs/ui/src/screens/welcome/welcome.test-ids.ts
  libs/ui/src/screens/welcome/welcome.tsx
Labels: ready for review

#198 [KL-368] Add load collectible with interval
  libs/ui/src/components/activity-section-list/activity-section-list.tsx
  libs/ui/src/components/collectible-image/collectible-image.styles.ts
  libs/ui/src/components/collectible-image/collectible-image.tsx
  libs/ui/src/components/icon/assets/loader-snake.svg
  libs/ui/src/components/icon/icon-name-map.ts
  libs/ui/src/components/icon/icon-name.enum.ts
  libs/ui/src/components/navigator/hooks/use-load-sent-collectibles-balance.hook.ts
  libs/ui/src/components/navigator/navigator.tsx
  libs/ui/src/interfaces/account.interface.ts
  libs/ui/src/modals/screens/collectible/collectible.tsx
  libs/ui/src/screens/collectibles/screens/specific-collectibles-list/specific-collectibles-list.tsx
  libs/ui/src/screens/send-confirmation/components/evm-confirmation/components/evm-confirmation-container/evm-confirmation-container.tsx
  libs/ui/src/screens/send-confirmation/components/tezos-confirmation/tezos-confirmation.tsx
  libs/ui/src/screens/send-confirmation/hooks/use-transaction.hook.tsx
  libs/ui/src/store/wallet/wallet.actions.ts
  libs/ui/src/store/wallet/wallet.epics.ts
  libs/ui/src/store/wallet/wallet.reducers.ts
  libs/ui/src/store/wallet/wallet.selectors.ts
  libs/ui/src/styles/colors.ts
  libs/ui/src/utils/by-network-types/token.utils.evm.ts
Labels: ready for review

#222 [KL-429] Add LICENSE
  LICENSE
Labels: ready for review

#223 [KL-423] Hide swap and top up
  libs/ui/src/components/navigation-bar/navigation-bar.test-ids.ts
  libs/ui/src/components/navigation-bar/navigation-bar.tsx
  libs/ui/src/enums/sreens.enum.ts
  libs/ui/src/screens/token/components/navigation-bar/constants.ts
  libs/ui/src/screens/wallet/components/assets-widget/assets-widget.styles.ts
  libs/ui/src/screens/wallet/components/assets-widget/assets-widget.tsx
Labels: ready for review

#226 [KL-429] Change license
  LICENSE
Labels: ready for review

#224 [KL-433] Add logo in extension
  apps/extension/public/manifest.json
  apps/extension/public/mics/logo128.png
  apps/extension/public/mics/logo16.png
  apps/extension/public/mics/logo192.png
  apps/extension/public/mics/logo48.png
  libs/ui/src/enums/sreens.enum.ts
Labels: ready for review, qa approve

#227 [KL-425] Fix gas limit on assets transaction
  libs/ui/src/components/navigator/hooks/use-reset-loading.hook.ts
  libs/ui/src/components/navigator/navigator.tsx
  libs/ui/src/screens/send-confirmation/components/evm-confirmation/constants/ethereum-gas-limit.ts
  libs/ui/src/screens/send-confirmation/components/evm-confirmation/hooks/use-evm-estimations.hook.ts
  libs/ui/src/screens/send-confirmation/components/evm-confirmation/utils/get-gas-limit.util.ts
  libs/ui/src/screens/send-confirmation/components/evm-confirmation/utils/modify-gas-limit.util.ts
  libs/ui/src/screens/send-confirmation/hooks/use-transaction.hook.tsx
Labels: qa approve

#230 KL-328 : fix promts
  libs/ui/src/modals/screens/network/components/network-container/network-container.tsx
Labels: qa approve

#232 KL-344 : fix navigation for dapp connection
  libs/ui/src/hooks/use-persisted-navigation-state.hook.ts
  libs/ui/src/screens/unlock-app/unlock-app.tsx
Labels: qa approve

#233 [KL-338] Fix network confirmation page
  apps/extension/public/manifest.json
  apps/extension/public/popup.html
  libs/ui/src/components/navigator/components/header-close-button/header-close-button.tsx
  libs/ui/src/components/navigator/components/header-title/header-title.tsx
  libs/ui/src/components/navigator/navigator.tsx
  libs/ui/src/modals/components/modal-container/modal-container.tsx
  libs/ui/src/modals/screens/network-change-confirmation/components/network-image/network-image.styles.ts
  libs/ui/src/modals/screens/network-change-confirmation/components/network-image/network-image.tsx
  libs/ui/src/modals/screens/network-change-confirmation/network-change-confirmation.styles.ts
  libs/ui/src/modals/screens/network-change-confirmation/network-change-confirmation.tsx
Labels: ready for review
